### PR TITLE
FIX/Editing similar process parameters

### LINKED ISSUE #891: UFAL/Health-reports editing the parameter after choosing action "Create similar process"
Editing the parameter after choosing the action "Create similar process" in the opened completed Health-report process will not save new (edited) parameters, but there is still an option to change it in the input fields.

Steps to reproduce the issue?
1. Create a health-report process with some check (e.g., "1")
2. Open the created process and click on the button `Create similar process`
3. Edit only the field with the check value (from "1" to "2") and save it
4. Open a newly created process and see if the "Arguments" section has your edited check or the old one (I see the old one)

Image
Image
Image

### PR DESCRIPTION
**Pull request by Paurikova2**
## Problem description
The values of the parameters are not changed when a similar process is created.

### CODE REVIEW

File: src/app/process-page/form/process-form.component.ts [hunk 1]
```diff
@@ -65,6 +65,20 @@ export class ProcessFormComponent implements OnInit {
...
+   * @param script The selected script
+   */
+  onScriptSelect(script: Script): void {
+    this.selectedScript = script;
+    // Clear parameters if we're not creating from an existing process
+    // (i.e., when no existing parameters or when switching to a different script)
+    if (!this.parameters) {
+      this.parameters = [];
+    }
+    // Note: If this.parameters has content, we preserve them for existing process recreation
```
Comment (milanmajchrak) [inline src/app/process-page/form/process-form.component.ts]: Remvoe this line

File: src/app/process-page/form/process-parameters/process-parameters.component.ts [hunk 2]
```diff
@@ -51,7 +52,17 @@ export class ProcessParametersComponent implements OnChanges {
...
     if (changes.script) {
-      this.initParameters();
+      // Only reset parameters if we don't have initial parameters to preserve
+      if (!hasValue(this.initialParams)) {
+        this.initParameters();
+      } else {
+        // If we have initial parameters, preserve them with deep copy
+        this.parameterValues = this.deepCopyParameters(this.initialParams);
+        // Only add an empty parameter if the list is empty or doesn't have a trailing empty parameter
+        if (this.parameterValues.length === 0 || hasValue(this.parameterValues[this.parameterValues.length - 1].name)) {
```
Comment (milanmajchrak) [inline src/app/process-page/form/process-parameters/process-parameters.component.ts:62]: Instead of this
```
hasValue(this.parameterValues[this.parameterValues.length - 1].name)
```

use this
```
hasValue(this.parameterValues.at(-1)?.name)
```

**Review by milanmajchrak — CHANGES_REQUESTED** [review]

**Review by milanmajchrak — APPROVED** [review]
