### PR TITLE
UFAL/License Administration Labels & Required Info checkboxes should work properly

### LINKED ISSUE #879: UFAL/License administration editing required user info problem
When editing required user info in licenses/manage-table with checkboxes, it does not work correctly.

_Previous issues: [#789](https://github.com/dataquest-dev/dspace-angular/issues/789), then [#857](https://github.com/dataquest-dev/dspace-angular/issues/857)
Previous fix: [#792](https://github.com/dataquest-dev/dspace-angular/pull/792), then [#863](https://github.com/dataquest-dev/dspace-angular/pull/863)_

Image

### PR DESCRIPTION
**Pull request by jr-rk**
| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
When editing required user info in licenses/manage-table with checkboxes, it does not work correctly. ID property of requiredInfo objects is ordered differently `after submit` and `while editing`.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved checkbox handling in license definition forms to prevent errors when removing items, ensuring more reliable form interactions.

### CODE REVIEW

**Comment by jr-rk** [comment]
@coderabbitai review

File: src/app/clarin-licenses/clarin-license-table/modal/define-license-form/define-license-form.component.ts [hunk 1]
```diff
@@ -169,8 +169,18 @@ export class DefineLicenseFormComponent implements OnInit {
     if (event.target.checked) {
       form.push(checkBoxValue);
     } else {
-      let index = form.findIndex(item => item.id === checkBoxValue.id);
-      form.splice(index, 1);
+      let index = -1;
```
Comment (milanmajchrak) [inline src/app/clarin-licenses/clarin-license-table/modal/define-license-form/define-license-form.component.ts]: The index is -1 by default when nothing is found. You do not need to initialize it.

Refactored code by the chatgpt, I like it:
```
  const index = form.findIndex(item =>
    item && (formName === 'requiredInfo'
      ? item.name === checkBoxValue.name
      : checkBoxValue.id === item.id)
  );

  if (index !== -1) {
    form.splice(index, 1);
  }
  ```

**Review by milanmajchrak — CHANGES_REQUESTED** [review]
